name: example
version: 1.0.0
description: Example for cinema rendering

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cutting_room:
    path: ../
  ffmpeg_cli: ^0.2.0
  logging: ^1.0.2

dev_dependencies:
  test: ^1.17.12
  flutter_lints: ^1.0.4
