name: cutting_room
version: 0.1.0
description: Compose and render videos with compositions, backed by FFMPEG.
homepage: https://github.com/Flutter-Bounty-Hunters/cutting_room

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffmpeg_cli: 0.1.0
  logging: ^1.0.2

dev_dependencies:
  test: ^1.17.12
  flutter_lints: ^1.0.4

